//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MessangerServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ChatDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPM {
            get {
                return this.IsPMField;
            }
            set {
                if ((this.IsPMField.Equals(value) != true)) {
                    this.IsPMField = value;
                    this.RaisePropertyChanged("IsPM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxUsers {
            get {
                return this.MaxUsersField;
            }
            set {
                if ((this.MaxUsersField.Equals(value) != true)) {
                    this.MaxUsersField = value;
                    this.RaisePropertyChanged("MaxUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class ClientDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MessangerServices.AccountDTO AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MessangerServices.AccountDTO Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class AccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFile", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class InfoFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class MessageDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MessangerServices.ChatDTO ChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MessangerServices.ClientDTO ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MessangerServices.ChatDTO Chat {
            get {
                return this.ChatField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatField, value) != true)) {
                    this.ChatField = value;
                    this.RaisePropertyChanged("Chat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChatId {
            get {
                return this.ChatIdField;
            }
            set {
                if ((this.ChatIdField.Equals(value) != true)) {
                    this.ChatIdField = value;
                    this.RaisePropertyChanged("ChatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MessangerServices.ClientDTO Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendingTime {
            get {
                return this.SendingTimeField;
            }
            set {
                if ((this.SendingTimeField.Equals(value) != true)) {
                    this.SendingTimeField = value;
                    this.RaisePropertyChanged("SendingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class MessageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MessangerServices.InfoFile[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MessangerServices.InfoFile[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessangerServices.IChatService")]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateNewChat", ReplyAction="http://tempuri.org/IChatService/CreateNewChatResponse")]
        Client.MessangerServices.ChatDTO CreateNewChat(Client.MessangerServices.ChatDTO newChatDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateNewChat", ReplyAction="http://tempuri.org/IChatService/CreateNewChatResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ChatDTO> CreateNewChatAsync(Client.MessangerServices.ChatDTO newChatDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : Client.MessangerServices.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.ClientBase<Client.MessangerServices.IChatService>, Client.MessangerServices.IChatService {
        
        public ChatServiceClient() {
        }
        
        public ChatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.MessangerServices.ChatDTO CreateNewChat(Client.MessangerServices.ChatDTO newChatDTO) {
            return base.Channel.CreateNewChat(newChatDTO);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ChatDTO> CreateNewChatAsync(Client.MessangerServices.ChatDTO newChatDTO) {
            return base.Channel.CreateNewChatAsync(newChatDTO);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessangerServices.IClientService", CallbackContract=typeof(Client.MessangerServices.IClientServiceCallback))]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CreateNewClient", ReplyAction="http://tempuri.org/IClientService/CreateNewClientResponse")]
        Client.MessangerServices.ClientDTO CreateNewClient(Client.MessangerServices.ClientDTO clientDTO, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CreateNewClient", ReplyAction="http://tempuri.org/IClientService/CreateNewClientResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO> CreateNewClientAsync(Client.MessangerServices.ClientDTO clientDTO, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetClient", ReplyAction="http://tempuri.org/IClientService/GetClientResponse")]
        Client.MessangerServices.ClientDTO GetClient(Client.MessangerServices.AccountDTO accountDTO, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetClient", ReplyAction="http://tempuri.org/IClientService/GetClientResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO> GetClientAsync(Client.MessangerServices.AccountDTO accountDTO, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SetProperties", ReplyAction="http://tempuri.org/IClientService/SetPropertiesResponse")]
        bool SetProperties(Client.MessangerServices.ClientDTO clientDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SetProperties", ReplyAction="http://tempuri.org/IClientService/SetPropertiesResponse")]
        System.Threading.Tasks.Task<bool> SetPropertiesAsync(Client.MessangerServices.ClientDTO clientDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SetPhoto", ReplyAction="http://tempuri.org/IClientService/SetPhotoResponse")]
        void SetPhoto(int clientId, Client.MessangerServices.InfoFile info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SetPhoto", ReplyAction="http://tempuri.org/IClientService/SetPhotoResponse")]
        System.Threading.Tasks.Task SetPhotoAsync(int clientId, Client.MessangerServices.InfoFile info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPhoto", ReplyAction="http://tempuri.org/IClientService/GetPhotoResponse")]
        Client.MessangerServices.InfoFile GetPhoto(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPhoto", ReplyAction="http://tempuri.org/IClientService/GetPhotoResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.InfoFile> GetPhotoAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPathToPhoto", ReplyAction="http://tempuri.org/IClientService/GetPathToPhotoResponse")]
        void GetPathToPhoto(string pathToPhoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPathToPhoto", ReplyAction="http://tempuri.org/IClientService/GetPathToPhotoResponse")]
        System.Threading.Tasks.Task GetPathToPhotoAsync(string pathToPhoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Disconnect", ReplyAction="http://tempuri.org/IClientService/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/Disconnect", ReplyAction="http://tempuri.org/IClientService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClientService/TakeMessage")]
        void TakeMessage(Client.MessangerServices.MessageDTO message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : Client.MessangerServices.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.DuplexClientBase<Client.MessangerServices.IClientService>, Client.MessangerServices.IClientService {
        
        public ClientServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ClientServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ClientServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Client.MessangerServices.ClientDTO CreateNewClient(Client.MessangerServices.ClientDTO clientDTO, string password) {
            return base.Channel.CreateNewClient(clientDTO, password);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO> CreateNewClientAsync(Client.MessangerServices.ClientDTO clientDTO, string password) {
            return base.Channel.CreateNewClientAsync(clientDTO, password);
        }
        
        public Client.MessangerServices.ClientDTO GetClient(Client.MessangerServices.AccountDTO accountDTO, string password) {
            return base.Channel.GetClient(accountDTO, password);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO> GetClientAsync(Client.MessangerServices.AccountDTO accountDTO, string password) {
            return base.Channel.GetClientAsync(accountDTO, password);
        }
        
        public bool SetProperties(Client.MessangerServices.ClientDTO clientDTO) {
            return base.Channel.SetProperties(clientDTO);
        }
        
        public System.Threading.Tasks.Task<bool> SetPropertiesAsync(Client.MessangerServices.ClientDTO clientDTO) {
            return base.Channel.SetPropertiesAsync(clientDTO);
        }
        
        public void SetPhoto(int clientId, Client.MessangerServices.InfoFile info) {
            base.Channel.SetPhoto(clientId, info);
        }
        
        public System.Threading.Tasks.Task SetPhotoAsync(int clientId, Client.MessangerServices.InfoFile info) {
            return base.Channel.SetPhotoAsync(clientId, info);
        }
        
        public Client.MessangerServices.InfoFile GetPhoto(int clientId) {
            return base.Channel.GetPhoto(clientId);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.InfoFile> GetPhotoAsync(int clientId) {
            return base.Channel.GetPhotoAsync(clientId);
        }
        
        public void GetPathToPhoto(string pathToPhoto) {
            base.Channel.GetPathToPhoto(pathToPhoto);
        }
        
        public System.Threading.Tasks.Task GetPathToPhotoAsync(string pathToPhoto) {
            return base.Channel.GetPathToPhotoAsync(pathToPhoto);
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public System.Threading.Tasks.Task DisconnectAsync() {
            return base.Channel.DisconnectAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessangerServices.IContactService")]
    public interface IContactService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactService/AddContact", ReplyAction="http://tempuri.org/IContactService/AddContactResponse")]
        Client.MessangerServices.ClientDTO AddContact(int clientID, string uniqueNameContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactService/AddContact", ReplyAction="http://tempuri.org/IContactService/AddContactResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO> AddContactAsync(int clientID, string uniqueNameContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactService/DeleteContact", ReplyAction="http://tempuri.org/IContactService/DeleteContactResponse")]
        bool DeleteContact(int clientID, string uniqueNameContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactService/DeleteContact", ReplyAction="http://tempuri.org/IContactService/DeleteContactResponse")]
        System.Threading.Tasks.Task<bool> DeleteContactAsync(int clientID, string uniqueNameContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactService/TakeContacts", ReplyAction="http://tempuri.org/IContactService/TakeContactsResponse")]
        Client.MessangerServices.ClientDTO[] TakeContacts(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactService/TakeContacts", ReplyAction="http://tempuri.org/IContactService/TakeContactsResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO[]> TakeContactsAsync(int clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactServiceChannel : Client.MessangerServices.IContactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactServiceClient : System.ServiceModel.ClientBase<Client.MessangerServices.IContactService>, Client.MessangerServices.IContactService {
        
        public ContactServiceClient() {
        }
        
        public ContactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.MessangerServices.ClientDTO AddContact(int clientID, string uniqueNameContact) {
            return base.Channel.AddContact(clientID, uniqueNameContact);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO> AddContactAsync(int clientID, string uniqueNameContact) {
            return base.Channel.AddContactAsync(clientID, uniqueNameContact);
        }
        
        public bool DeleteContact(int clientID, string uniqueNameContact) {
            return base.Channel.DeleteContact(clientID, uniqueNameContact);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteContactAsync(int clientID, string uniqueNameContact) {
            return base.Channel.DeleteContactAsync(clientID, uniqueNameContact);
        }
        
        public Client.MessangerServices.ClientDTO[] TakeContacts(int clientId) {
            return base.Channel.TakeContacts(clientId);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO[]> TakeContactsAsync(int clientId) {
            return base.Channel.TakeContactsAsync(clientId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessangerServices.IChatMemberService")]
    public interface IChatMemberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/JoinToChat", ReplyAction="http://tempuri.org/IChatMemberService/JoinToChatResponse")]
        Client.MessangerServices.ChatDTO JoinToChat(int clientId, string chatUniqueName, bool isAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/JoinToChat", ReplyAction="http://tempuri.org/IChatMemberService/JoinToChatResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ChatDTO> JoinToChatAsync(int clientId, string chatUniqueName, bool isAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/LeaveFromChat", ReplyAction="http://tempuri.org/IChatMemberService/LeaveFromChatResponse")]
        bool LeaveFromChat(int clientId, int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/LeaveFromChat", ReplyAction="http://tempuri.org/IChatMemberService/LeaveFromChatResponse")]
        System.Threading.Tasks.Task<bool> LeaveFromChatAsync(int clientId, int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/TakeChats", ReplyAction="http://tempuri.org/IChatMemberService/TakeChatsResponse")]
        Client.MessangerServices.ChatDTO[] TakeChats(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/TakeChats", ReplyAction="http://tempuri.org/IChatMemberService/TakeChatsResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ChatDTO[]> TakeChatsAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/TakeClients", ReplyAction="http://tempuri.org/IChatMemberService/TakeClientsResponse")]
        Client.MessangerServices.ClientDTO[] TakeClients(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatMemberService/TakeClients", ReplyAction="http://tempuri.org/IChatMemberService/TakeClientsResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO[]> TakeClientsAsync(int chatId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatMemberServiceChannel : Client.MessangerServices.IChatMemberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatMemberServiceClient : System.ServiceModel.ClientBase<Client.MessangerServices.IChatMemberService>, Client.MessangerServices.IChatMemberService {
        
        public ChatMemberServiceClient() {
        }
        
        public ChatMemberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatMemberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatMemberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatMemberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.MessangerServices.ChatDTO JoinToChat(int clientId, string chatUniqueName, bool isAdmin) {
            return base.Channel.JoinToChat(clientId, chatUniqueName, isAdmin);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ChatDTO> JoinToChatAsync(int clientId, string chatUniqueName, bool isAdmin) {
            return base.Channel.JoinToChatAsync(clientId, chatUniqueName, isAdmin);
        }
        
        public bool LeaveFromChat(int clientId, int chatId) {
            return base.Channel.LeaveFromChat(clientId, chatId);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveFromChatAsync(int clientId, int chatId) {
            return base.Channel.LeaveFromChatAsync(clientId, chatId);
        }
        
        public Client.MessangerServices.ChatDTO[] TakeChats(int clientId) {
            return base.Channel.TakeChats(clientId);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ChatDTO[]> TakeChatsAsync(int clientId) {
            return base.Channel.TakeChatsAsync(clientId);
        }
        
        public Client.MessangerServices.ClientDTO[] TakeClients(int chatId) {
            return base.Channel.TakeClients(chatId);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.ClientDTO[]> TakeClientsAsync(int chatId) {
            return base.Channel.TakeClientsAsync(chatId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessangerServices.IMessageService", CallbackContract=typeof(Client.MessangerServices.IMessageServiceCallback))]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/SendMessage")]
        void SendMessage(int clientId, int chatId, Client.MessangerServices.MessageInfo message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(int clientId, int chatId, Client.MessangerServices.MessageInfo message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/TakeMessages", ReplyAction="http://tempuri.org/IMessageService/TakeMessagesResponse")]
        Client.MessangerServices.MessageDTO[] TakeMessages(int chatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/TakeMessages", ReplyAction="http://tempuri.org/IMessageService/TakeMessagesResponse")]
        System.Threading.Tasks.Task<Client.MessangerServices.MessageDTO[]> TakeMessagesAsync(int chatId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessageService/TakeMessage")]
        void TakeMessage(Client.MessangerServices.MessageDTO message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : Client.MessangerServices.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.DuplexClientBase<Client.MessangerServices.IMessageService>, Client.MessangerServices.IMessageService {
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessage(int clientId, int chatId, Client.MessangerServices.MessageInfo message) {
            base.Channel.SendMessage(clientId, chatId, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(int clientId, int chatId, Client.MessangerServices.MessageInfo message) {
            return base.Channel.SendMessageAsync(clientId, chatId, message);
        }
        
        public Client.MessangerServices.MessageDTO[] TakeMessages(int chatId) {
            return base.Channel.TakeMessages(chatId);
        }
        
        public System.Threading.Tasks.Task<Client.MessangerServices.MessageDTO[]> TakeMessagesAsync(int chatId) {
            return base.Channel.TakeMessagesAsync(chatId);
        }
    }
}
