//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept.
        /// </summary>
        public static string AcceptButtonString {
            get {
                return ResourceManager.GetString("AcceptButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string AddEditChatDialogButtonCreateString {
            get {
                return ResourceManager.GetString("AddEditChatDialogButtonCreateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string AddEditChatDialogButtonEditString {
            get {
                return ResourceManager.GetString("AddEditChatDialogButtonEditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is private chat.
        /// </summary>
        public static string AddEditChatDialogIsPrivateChatString {
            get {
                return ResourceManager.GetString("AddEditChatDialogIsPrivateChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Private messages.
        /// </summary>
        public static string AddEditChatDialogPM {
            get {
                return ResourceManager.GetString("AddEditChatDialogPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select chat photo.
        /// </summary>
        public static string AddEditChatDialogSelectChatPhotoButtonString {
            get {
                return ResourceManager.GetString("AddEditChatDialogSelectChatPhotoButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButtonString {
            get {
                return ResourceManager.GetString("CancelButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat Info.
        /// </summary>
        public static string ChatViewChatInfoDialogHeaderChatInfoString {
            get {
                return ResourceManager.GetString("ChatViewChatInfoDialogHeaderChatInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Info.
        /// </summary>
        public static string ChatViewProfileDialogHeaderUserInfoString {
            get {
                return ResourceManager.GetString("ChatViewProfileDialogHeaderUserInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add contact.
        /// </summary>
        public static string ContactsDialogAddContactString {
            get {
                return ResourceManager.GetString("ContactsDialogAddContactString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete contact.
        /// </summary>
        public static string ContactsDialogDeleteContactString {
            get {
                return ResourceManager.GetString("ContactsDialogDeleteContactString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        public static string ContactsDialogHeaderString {
            get {
                return ResourceManager.GetString("ContactsDialogHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select photo.
        /// </summary>
        public static string EditProfileDialogSetProfilePhotoButtonString {
            get {
                return ResourceManager.GetString("EditProfileDialogSetProfilePhotoButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EmailString {
            get {
                return ResourceManager.GetString("EmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error. Not all fields were filled..
        /// </summary>
        public static string EmptyFieldsString {
            get {
                return ResourceManager.GetString("EmptyFieldsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact could not be added..
        /// </summary>
        public static string FailedContactAddString {
            get {
                return ResourceManager.GetString("FailedContactAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete contact..
        /// </summary>
        public static string FailedContactDeletedString {
            get {
                return ResourceManager.GetString("FailedContactDeletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat was not created..
        /// </summary>
        public static string FailedCreateChatString {
            get {
                return ResourceManager.GetString("FailedCreateChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join to chat failed..
        /// </summary>
        public static string FailedJoinToChatString {
            get {
                return ResourceManager.GetString("FailedJoinToChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave from chat failed..
        /// </summary>
        public static string FailedLeaveFromChatString {
            get {
                return ResourceManager.GetString("FailedLeaveFromChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It looks like our system does not have a user with enetered data. Please, try again..
        /// </summary>
        public static string FailedLoginString {
            get {
                return ResourceManager.GetString("FailedLoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data has not been changed..
        /// </summary>
        public static string FailedSetChatPropertiesString {
            get {
                return ResourceManager.GetString("FailedSetChatPropertiesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data has not been changed..
        /// </summary>
        public static string FailedSetProfileString {
            get {
                return ResourceManager.GetString("FailedSetProfileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration problems. Try to change data..
        /// </summary>
        public static string FailedSignUpString {
            get {
                return ResourceManager.GetString("FailedSignUpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information diolog.
        /// </summary>
        public static string InformationDialogHeaderInformationDialogString {
            get {
                return ResourceManager.GetString("InformationDialogHeaderInformationDialogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string InformationDialogOKButtonString {
            get {
                return ResourceManager.GetString("InformationDialogOKButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chats.
        /// </summary>
        public static string JoinChatDialogHeaderChatsString {
            get {
                return ResourceManager.GetString("JoinChatDialogHeaderChatsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join.
        /// </summary>
        public static string JoinChatDialogJoin {
            get {
                return ResourceManager.GetString("JoinChatDialogJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LanguageString {
            get {
                return ResourceManager.GetString("LanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave the chat.
        /// </summary>
        public static string LeaveTheChatButtonString {
            get {
                return ResourceManager.GetString("LeaveTheChatButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        public static string LeftPanelContactsButtonString {
            get {
                return ResourceManager.GetString("LeftPanelContactsButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit profile.
        /// </summary>
        public static string LeftPanelEditProfileButtonString {
            get {
                return ResourceManager.GetString("LeftPanelEditProfileButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string LeftPanelExitButtonString {
            get {
                return ResourceManager.GetString("LeftPanelExitButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join to chat.
        /// </summary>
        public static string LeftPanelJoinToChatButtonString {
            get {
                return ResourceManager.GetString("LeftPanelJoinToChatButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New chat.
        /// </summary>
        public static string LeftPanelNewChatButtonString {
            get {
                return ResourceManager.GetString("LeftPanelNewChatButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already have an account.
        /// </summary>
        public static string LoginDialogGoToLogInString {
            get {
                return ResourceManager.GetString("LoginDialogGoToLogInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t have an account.
        /// </summary>
        public static string LoginDialogGoToSignUpString {
            get {
                return ResourceManager.GetString("LoginDialogGoToSignUpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginDialogHeaderLoginString {
            get {
                return ResourceManager.GetString("LoginDialogHeaderLoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign up.
        /// </summary>
        public static string LoginDialogHeaderSignUpString {
            get {
                return ResourceManager.GetString("LoginDialogHeaderSignUpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        public static string LoginDialogLoginButtonString {
            get {
                return ResourceManager.GetString("LoginDialogLoginButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign up.
        /// </summary>
        public static string LoginDialogSignUpButtonString {
            get {
                return ResourceManager.GetString("LoginDialogSignUpButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage chat.
        /// </summary>
        public static string ManageChatButtonString {
            get {
                return ResourceManager.GetString("ManageChatButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum number of members.
        /// </summary>
        public static string MaxNumOfMembersString {
            get {
                return ResourceManager.GetString("MaxNumOfMembersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на members.
        /// </summary>
        public static string MembersString {
            get {
                return ResourceManager.GetString("MembersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat name.
        /// </summary>
        public static string NameChatSrting {
            get {
                return ResourceManager.GetString("NameChatSrting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add chat.
        /// </summary>
        public static string NewChatDialogAddChatButtonString {
            get {
                return ResourceManager.GetString("NewChatDialogAddChatButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string PhoneString {
            get {
                return ResourceManager.GetString("PhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact added successfully..
        /// </summary>
        public static string SuccessfulContactAddString {
            get {
                return ResourceManager.GetString("SuccessfulContactAddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact successfully delete..
        /// </summary>
        public static string SuccessfulContactDeleteString {
            get {
                return ResourceManager.GetString("SuccessfulContactDeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat successsfully created..
        /// </summary>
        public static string SuccessfulCreateChatString {
            get {
                return ResourceManager.GetString("SuccessfulCreateChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join to chat successsfully..
        /// </summary>
        public static string SuccessfulJoinToChatString {
            get {
                return ResourceManager.GetString("SuccessfulJoinToChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave from chat successsfully..
        /// </summary>
        public static string SuccessfulLeaveFromChatString {
            get {
                return ResourceManager.GetString("SuccessfulLeaveFromChatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login successful. 
        ///Hi, .
        /// </summary>
        public static string SuccessfulLoginString {
            get {
                return ResourceManager.GetString("SuccessfulLoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat settings successfully changed..
        /// </summary>
        public static string SuccessfulSetChatPropertiesString {
            get {
                return ResourceManager.GetString("SuccessfulSetChatPropertiesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data changed successfully..
        /// </summary>
        public static string SuccessfulSetProfileString {
            get {
                return ResourceManager.GetString("SuccessfulSetProfileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration successful. 
        ///Welcome, .
        /// </summary>
        public static string SuccessfulSignUpString {
            get {
                return ResourceManager.GetString("SuccessfulSignUpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unique name.
        /// </summary>
        public static string UniqueNameString {
            get {
                return ResourceManager.GetString("UniqueNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View chat info.
        /// </summary>
        public static string ViewChatInfoButtonString {
            get {
                return ResourceManager.GetString("ViewChatInfoButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View profile.
        /// </summary>
        public static string ViewProfileButtonString {
            get {
                return ResourceManager.GetString("ViewProfileButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write a message....
        /// </summary>
        public static string WriteMessageString {
            get {
                return ResourceManager.GetString("WriteMessageString", resourceCulture);
            }
        }
    }
}
